export const DEFAULT_HYBRID_LOWER_PERCENT = 5;
export const DEFAULT_HYBRID_UPPER_PERCENT = 95;
export const DEFAULT_WORKING_DAYS = 240;

// these are normalised...
export const DEFAULT_HYBRID_LOWER = DEFAULT_HYBRID_LOWER_PERCENT / 100;
export const DEFAULT_HYBRID_UPPER = DEFAULT_HYBRID_UPPER_PERCENT / 100;
